const level = require('../../src/entities/level')
const members = require('../../src/entities/member')
const Team = require('../../src/entities/team')
const Sorter = require('../../src/helpers/sorter')

const sorter = new Sorter()

const memberA = members.createMember(0, "juan", 0)
const memberB = members.createMember(1, "fran", 2)
const memberC = members.createMember(2, "fran2", 1)
const memberD = members.createMember(3, "fran3", 2)
const memberE = members.createMember(4, "fran4", 1)
const memberF = members.createMember(5, "fran5", 2)
const memberG = members.createMember(6, "fran6", 1)
const memberH = members.createMember(7, "fran7", 2)
const memberI = members.createMember(8, "fran8", 1)

test('show level names', () => {
    sorter.setTeamSize(3)
    sorter.addMember(memberA)
    sorter.addMember(memberB)
    sorter.addMember(memberC)
    sorter.addMember(memberD)
    sorter.addMember(memberE)
    sorter.addMember(memberF)
    sorter.addMember(memberG)
    sorter.addMember(memberH)
    sorter.addMember(memberI)
    expect(team.getTeams().size.toBe(3))
});
